### ISSUE TITLE
我执行python manager.py runserver 在服务器上报错

### ISSUE THREAD

**Issue by sohu56James** [zhuima/daohang#27]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

如下：

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.5/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/simpleui/admin.py", line 91
    raise Exception(f'action "{_action}" not found')
                                                  ^
SyntaxError: invalid syntax

**Comment by sohu56James** [comment]
请问是不是我的环境有问题导致的？

**Comment by changchunhua2017** [comment]
我也是，docker 拉了  latest  / v0.0.5 / v0.0.4 镜像都run 测过了，根本跑不起来 ，报错一样 
raise Exception(f'action "{_action}" not found')

项目大大帮忙看看啊

**Comment by zhuima** [comment]
> 我也是，docker 拉了 latest / v0.0.5 / v0.0.4 镜像都run 测过了，根本跑不起来 ，报错一样 raise Exception(f'action "{_action}" not found')
> 
> 项目大大帮忙看看啊 @zhuima

问题修复，你可以自己本地构建，或者直接使用最新的镜像，或者使用我上传到hub的镜像 docker pull zhuima314/daohang:v0.0.7

**Comment by zhuima** [comment]
> 请问是不是我的环境有问题导致的？

你这个是python版本吧，要求3.5或以上版本才行，换下python版本再试下，docker镜像的问题我已经修复了
